# Generated by Django 3.0 on 2021-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elliptical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalCapsule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalCylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalDishedEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalElliptical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('InsideDiameter', models.IntegerField()),
                ('OutsideDiameter', models.IntegerField()),
                ('TankClass', models.CharField(max_length=10)),
                ('thickness', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalOval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RectangularTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torispherical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('InsideDiameter', models.IntegerField()),
                ('OutsideDiameter', models.IntegerField()),
                ('TankClass', models.CharField(max_length=10)),
                ('thickness', models.IntegerField()),
                ('KnuckleRadius', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerticalCapsule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerticalCylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerticalOval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
    ]
