# Generated by Django 3.0 on 2021-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorCyl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorEllip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HorOval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SideLength', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerCyl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerOval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('filled', models.IntegerField()),
            ],
        ),
    ]
