# Generated by Django 3.0 on 2021-03-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcvol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horcyl',
            name='height',
        ),
    ]
